server:
  port: 8085

spring:
  application:
    name: business
  profiles:
    active: dev #切换开发环境和测试环境，dev为开发环境，prod为测试环境
  #数据库连接信息
  datasource:
    name:  business
    type: com.alibaba.druid.pool.DruidDataSource
    #项目启动后执行建表语句
    schema:
      - classpath:sql/data.sql
    sql-script-encoding: utf-8
    platform: mysql
    initialization-mode: always
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat,wall
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性  qpmz
      url: jdbc:mysql://business-db:3306/business?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 300000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 1800000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.sunny.business.pojo # 注意：对应实体类的路径
#  config-location: classpath:mybatis-config.xml
mapper:
  mappers: com.sunny.business.repository.base.MyBaseDao
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql





