
networks:
  business-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
services:
  business1:
    build:
      context: /usr/local/business
    container_name: business-service1
    image: business-image
    networks:
      business-net:
        ipv4_address: 172.18.0.3
    ports:
      - 8086:8085/tcp
    restart: always
  business2:
    build:
      context: /usr/local/business
    container_name: business-service2
    image: business-image
    networks:
      business-net:
        ipv4_address: 172.18.0.4
    ports:
      - 8087:8085/tcp
    restart: always
  business3:
    build:
      context: /usr/local/business
    container_name: business-service3
    image: business-image
    networks:
      business-net:
        ipv4_address: 172.18.0.5
    ports:
      - 8088:8085/tcp
    restart: always
  mysql:
    build:
      context: /usr/local/business
    container_name: business-db
    environment:
      MYSQL_DATABASE: business
      MYSQL_ROOT_PASSWORD: 123456
    image: mysql
    networks:
      business-net:
        ipv4_address: 172.18.0.2
    ports:
      - 3301:3306/tcp
    restart: always
    volumes:
      - business-volume:/var/lib/mysql:rw
  nginx:
    build:
      context: /usr/local/business
    container_name: business-nginx
    image: nginx
    networks:
      business-net:
        ipv4_address: 172.18.0.6
    ports:
      - 80:80/tcp
    restart: always
    volumes:
      - /usr/local/business/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
version: '3.0'
volumes:
  business-volume: {}